Add an option to exclude private IP addresses from zone files
unioslo/mreg pull request #479
Opened 2023-02-10 15:04 UTC by oyvindhagberg

This PR adds a query parameter to the zonefile API endpoint that causes mreg to exclude all IP addresses in private address spaces (see [RFC1918](https://www.rfc-editor.org/rfc/rfc1918#section-3)) from the exported zone file.
In short, the address ranges are:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16

Also, the PR updates requirements.txt with newer versions of some libraries.

The reason behind this is that [Services for sensitive data (TSD)](https://www.uio.no/english/services/it/research/sensitive-data/) are using mreg to create zone files for their DNS server, and they are using private IPv4 addresses internally. They want their DNS server to respond differently depending on whether the request comes from within their own network or from outside.

2023-02-13 12:51 UTC, oyvindkolbu requested changes

2023-02-15 13:48 UTC, oyvindhagberg commented on mreg/api/v1/zonefile.py
> +                                   .exclude(ipaddress__range=('192.168.0.0','192.168.255.255'))
1. The requested feature is to filter out private address spaces as defined in RFC1918, not any arbitrary list of networks. No need to put the ranges in a config file. 
2. The code is not expected to run often enough or over enough data that execution speed will be an issue. And if it does, the problem will be limited to the environments where this new option will be used. Premature optimization is usually not a good thing.
3. Do you have a particular style guide in mind?

2023-02-15 19:55 UTC, oyvindkolbu commented on mreg/api/v1/zonefile.py
> +                                   .exclude(ipaddress__range=('192.168.0.0','192.168.255.255'))
> 1. The requested feature is to filter out private address spaces as defined in RFC1918, not any arbitrary list of networks. No need to put the ranges in a config file.

Still no reason to limit to those ranges or hardcode them. A setting with list of CIDRs seems much better.

> 2. The code is not expected to run often enough or over enough data that execution speed will be an issue. And if it does, the problem will be limited to the environments where this new option will be used. Premature optimization is usually not a good thing.

This function and in general the `zonefile.py` file is the most optimized file in the entire project. It is not by chance the zonefiles are generated in a couple of seconds.

> 3. Do you have a particular style guide in mind?

No, but just a space after a comma in function arguments is easy on the eyes.

2023-02-24 10:40 UTC, oyvindhagberg commented on mreg/api/v1/zonefile.py
> +                                   .exclude(ipaddress__range=('192.168.0.0','192.168.255.255'))
I ran a benchmark using the [code here](https://gist.github.com/oyvindhagberg/41de9b9a88155e285551272b30771667). It seems the zonefile export runs slightly *faster* when filtering out private ip addresses. Any thoughts?

2023-02-24 10:44 UTC, oyvindkolbu commented on mreg/api/v1/zonefile.py
> +                                   .exclude(ipaddress__range=('192.168.0.0','192.168.255.255'))
Makes sense that is faster to ignore data than process it.

2023-03-01 12:38 UTC, merged